@startuml mapping_2d





/' Objects '/


class ActiveSubmaps2D {
}



class CollatedTrajectoryBuilder {
}


abstract class Grid2D {
}


class ImuBasedPoseExtrapolator {

}

class ImuTracker {
}


class LocalSlamResult2D {
}

abstract class LocalSlamResultData {
	+{abstract} AddToTrajectoryBuilder(TrajectoryBuilderInterface* const trajectory_builder) : void 
	+{abstract} AddToPoseGraph(int trajectory_id, PoseGraph* pose_graph)  : void 

}

class LocalTrajectoryBuilder2D {
}


class MapBuilder {

}

abstract class MapBuilderInterface {

	+{abstract} pose_graph() : PoseGraphInterface*

	+{abstract} AddTrajectoryBuilder(...) : int
	+{abstract} AddTrajectoryForDeserialization(const proto::TrajectoryBuilderOptionsWithSensorIds& options_with_sensor_ids_proto) : int
	+{abstract} GetAllTrajectoryBuilderOptions() : std::vector<proto::TrajectoryBuilderOptionsWithSensorIds>& {query}
	+{abstract} GetTrajectoryBuilder(int trajectory_id) : TrajectoryBuilderInterface* {query}
	+{abstract} FinishTrajectory(int trajectory_id) : void

	+{abstract} SerializeStateToFile(bool include_unfinished_submaps, const std::string& filename) : bool
	+{abstract} SerializeState(bool include_unfinished_submaps, io::ProtoStreamWriterInterface* writer) : void
	+{abstract} LoadState(io::ProtoStreamReaderInterface* reader, bool load_frozen_state) : std::map<int , int>
	+{abstract} LoadStateFromFile(const std::string& filename, bool load_frozen_state) : std::map<int , int>
	+{abstract} SubmapToProto(const SubmapId& submap_id, proto::SubmapQuery::Response* response) : std::string

}


class MotionFilter {

}



class OverlappingSubmapsTrimmer2D {

}

class PoseExtrapolator {

}

abstract class PoseExtrapolatorInterface {

}

abstract class PoseGraph {

}

class PoseGraph2D {

}


abstract class PoseGraphInterface {
	+{abstract} RunFinalOptimization() : void

	+{abstract} GetAllSubmapData() : MapById<SubmapId, SubmapData>
	+{abstract} GetAllSubmapPoses() : MapById<SubmapId, SubmapPose>
	+{abstract} GetLocalToGlobalTransform(int trajectory_id) : transform::Rigid3d
	+{abstract} GetLandmarkPoses() : std::map<std::string, transform::Rigid3d>

	+{abstract} GetTrajectoryNodes() : MapById<NodeId, TrajectoryNode>
	+{abstract} GetTrajectoryNodePoses() : MapById<NodeId, TrajectoryNodePose>
	+{abstract} DeleteTrajectory(int trajectory_id) : void
	+{abstract} IsTrajectoryFinished(int trajectory_id) : bool
	+{abstract} IsTrajectoryFrozen(int trajectory_id) : bool
	+{abstract} GetTrajectoryData() : std::map<int, TrajectoryData>

	+{abstract} constraints() : std::vector<Constraint>
	+{abstract} SetGlobalSlamOptimizationCallback(GlobalSlamOptimizationCallback callback) : void
}

abstract class PoseGraphTrimmer {
}

class ProbabilityGrid {
}


class PureLocalizationTrimmer {
}

class RangeDataCollator {
}


abstract class Submap {
}

class Submap2D {
}



abstract class TrajectoryBuilderInterface {
	+{abstract} AddLocalSlamResultData(std::unique_ptr<LocalSlamResultData> local_slam_result_data) : void
	+{abstract} AddSensorData(const std::string& sensor_id, const sensor::TimedPointCloudData& timed_point_cloud_data) : void
	+{abstract} AddSensorData(const std::string& sensor_id, const sensor::ImuData& imu_data) : void
	+{abstract} AddSensorData(const std::string& sensor_id, const sensor::OdometryData& odometry_data) : void
	+{abstract} AddSensorData(const std::string& sensor_id, const sensor::FixedFramePoseData& fixed_frame_pose) : void
	+{abstract} AddSensorData(const std::string& sensor_id, const sensor::LandmarkData& landmark_data) : void
}

namespace scan_matching {
	class CeresScanMatcher2D {
	}

	class RealTimeCorrelativeScanMatcher2D {}


}

namespace optimization {


	class OptimizationProblem2D {
	}

	abstract class OptimizationProblemInterface   {
		+{abstract} node_data() : MapById<NodeId , NodeDataType>& {query}
		+{abstract} submap_data() : MapById<SubmapId , SubmapDataType>& {query}
		+{abstract} imu_data() : sensor::MapByTime<sensor::ImuData>& {query}
		+{abstract} odometry_data() : sensor::MapByTime<sensor::OdometryData>& {query}
		+{abstract} landmark_data() : std::map<std::string , transform::Rigid3d>& {query}
		+{abstract} AddImuData(int trajectory_id, const sensor::ImuData& imu_data) : void
		+{abstract} AddOdometryData(int trajectory_id, const sensor::OdometryData& odometry_data) : void
		+{abstract} AddSubmap(int trajectory_id, const RigidTransformType& global_submap_pose) : void
		+{abstract} AddTrajectoryNode(int trajectory_id, const NodeDataType& node_data) : void
		+{abstract} InsertSubmap(const SubmapId& submap_id, const RigidTransformType& global_submap_pose) : void
		+{abstract} InsertTrajectoryNode(const NodeId& node_id, const NodeDataType& node_data) : void
		+{abstract} SetMaxNumIterations(int max_num_iterations) : void
		+{abstract} Solve(const std::vector<Constraint>& constraints, & trajectories_state,  & landmark_nodes) : void
		+{abstract} TrimSubmap(const SubmapId& submap_id) : void
		+{abstract} TrimTrajectoryNode(const NodeId& node_id) : void
	}
}

namespace constraints {
	abstract class ConstraintBuilder2D {
		+ConstraintBuilder2D(const proto::ConstraintBuilderOptions& options, common::ThreadPoolInterface* thread_pool)
		-function<void(vector<Constraint> mutex_)
		+~ConstraintBuilder2D()
		-DispatchScanMatcherConstruction(const SubmapId& submap_id, const Grid2D* grid ) EXCLUSIVE_LOCKS_REQUIRED ( mutex_) : SubmapScanMatcher*
		-mutex_ : absl::Mutex
		-GUARDED_BY(mutex_) : common::Histogram score_histogram_
		-thread_pool_ : common::ThreadPoolInterface*
		-options_ : const constraints::proto::ConstraintBuilderOptions
		+GetNumFinishedNodes() : int
		-RunWhenDoneCallback() LOCKS_EXCLUDED ( mutex_) : void
		+WhenDone(const std::function<void ( const Result& )>& callback) : void
	}

}








/' Inheritance relationships '/

Grid2D <|-- ProbabilityGrid


LocalSlamResultData <|.. LocalSlamResult2D

namespace sensor {
abstract class CollatorInterface{
}
}


MapBuilderInterface <|.. MapBuilder

MapBuilder *-- common.ThreadPool
MapBuilder *-- sensor.CollatorInterface


optimization.OptimizationProblemInterface <|.. optimization.OptimizationProblem2D




PoseExtrapolatorInterface <|.. ImuBasedPoseExtrapolator


PoseExtrapolatorInterface <|.. PoseExtrapolator

PoseExtrapolator *-- ImuTracker


PoseGraph <|-- PoseGraph2D

PoseGraph2D *-- WorkQueue 
PoseGraph2D *-- optimization.OptimizationProblem2D
PoseGraph2D *-- constraints.ConstraintBuilder2D
PoseGraph2D *-- PoseGraphData
PoseGraph2D *-- PoseGraphTrimmer

PoseGraph2D o-- common.ThreadPool


PoseGraphInterface <|.. PoseGraph


PoseGraphTrimmer <|-- OverlappingSubmapsTrimmer2D


PoseGraphTrimmer <|-- PureLocalizationTrimmer


' constraints.ConstraintBuilder2D o-- common.ThreadPool
constraints.ConstraintBuilder2D *-- scan_matching.CeresScanMatcher2D 

Submap <|-- Submap2D



TrajectoryBuilderInterface <|-- CollatedTrajectoryBuilder


' Trimmable <|-- PoseGraph2D::TrimmingHandle






/' Aggregation relationships '/


ActiveSubmaps2D o-- Submap2D


LocalSlamResult2D *-- Submap2D

LocalTrajectoryBuilder2D *-- ActiveSubmaps2D


LocalTrajectoryBuilder2D *-- scan_matching.CeresScanMatcher2D


LocalTrajectoryBuilder2D *-- MotionFilter


LocalTrajectoryBuilder2D *-- PoseExtrapolator


LocalTrajectoryBuilder2D *-- RangeDataCollator


LocalTrajectoryBuilder2D *-- scan_matching.RealTimeCorrelativeScanMatcher2D


MapBuilder o-- PoseGraph


MapBuilder *-- TrajectoryBuilderInterface

TrajectoryBuilderInterface *-- LocalSlamResultData


optimization.OptimizationProblem2D *-- optimization.NodeSpec2D


optimization.OptimizationProblem2D *-- optimization.SubmapSpec2D



Submap2D o-- Grid2D




class GlobalTrajectoryBuilder<LocalTrajectoryBuilder2D,PoseGraph2D>{

}

GlobalTrajectoryBuilder ..|>  TrajectoryBuilderInterface

GlobalTrajectoryBuilder *-- LocalTrajectoryBuilder2D
GlobalTrajectoryBuilder o-- PoseGraph2D
GlobalTrajectoryBuilder o-- MotionFilter





@enduml
